### ISSUE TITLE
Crash when replacing an element

### ISSUE THREAD

**Issue by mrakgr** [AnthonyLloyd/Elm#1]
```
    let view (model:Model) :Msg UI =
        UI.div Horizontal [
            UI.button "+" Increment
            UI.button "-" Decrement
            UI.text (string model)
            (if model > 5 then UI.text "Bigger than 5." else UI.button "+" Increment)
        ]
```

In the modified counter example above it crashes when I raise the counter above 5. Stepping through it, I've located the bug in ...

```
    let rec locatePanel loc : Panel =
        match loc with
        |[] -> root.Content :?> _
        |i::xs -> (locatePanel xs).Children.Item i :?> _
```

...the `locatePanel` function, on the last line, but I do not understand this code well enough to fix it yet.

**Comment by AnthonyLloyd** [comment]
Thank you for this. I can only think there is a bug in ReplaceUI.

I'm on holiday now but will look at it as soon as I'm back in 2 week.
